version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: citas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: citas_medicasBD
    ports:
      - "3307:3306"  # Puerto 3307 en tu host para evitar conflictos
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - citas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: citas_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/citas_medicasBD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - citas-network

volumes:
  mysql_data:

networks:
  citas-network:
    driver: bridge
